### ISSUE TITLE
Upgrade to AJV 7 with Standalone

### ISSUE THREAD

**Issue by taras** [downace/ajv-json-loader#6]
We came across this library in the process of researching an [issue with NetlifyCMS](https://github.com/netlify/netlify-cms/issues/2138). We would like to use this library to resolve the issue. 

Would you accept a PR to upgrade to use [AJV 7 and Standalone](https://ajv.js.org/standalone.html) mode instead of ajv-pack?

**Comment by downace** [comment]
Hi!

Yes, sure. That sounds good.

Also this change is worth bumping the package version to 1.0.0.

**Comment by downace** [comment]
Closing this as fixed via #7
